// resources/js/data.js
export const products = [
    {
        id: 1,
        name: "Sony Alpha A7 IV",
        brand: "Sony",
        cat: "Mirrorless",
        price: 250000,
        deposit: 750000,
        rating: 4.9,
        reviews: 48,
        hot: true,
        isNew: true,
        avail: true,
        icon: "📷",
        desc: "Kamera mirrorless full-frame flagship Sony dengan sensor 33MP dan prosesor BIONZ XR terbaru.",
    },
    {
        id: 2,
        name: "Canon EOS R5",
        brand: "Canon",
        cat: "Mirrorless",
        price: 300000,
        deposit: 900000,
        rating: 4.8,
        reviews: 36,
        hot: true,
        isNew: false,
        avail: true,
        icon: "📷",
        desc: "Flagship mirrorless Canon dengan resolusi 45MP dan kemampuan video 8K RAW internal.",
    },
    {
        id: 3,
        name: "Nikon Z6 II",
        brand: "Nikon",
        cat: "Mirrorless",
        price: 200000,
        deposit: 600000,
        rating: 4.7,
        reviews: 29,
        hot: false,
        isNew: false,
        avail: true,
        icon: "📷",
        desc: "Mirrorless full-frame Nikon serbaguna untuk foto dan video.",
    },
    {
        id: 4,
        name: "Fujifilm X-T5",
        brand: "Fujifilm",
        cat: "Mirrorless",
        price: 180000,
        deposit: 540000,
        rating: 4.9,
        reviews: 52,
        hot: true,
        isNew: true,
        avail: true,
        icon: "📸",
        desc: "Kamera APS-C 40MP terbaru Fujifilm dengan 20 film simulation iconic.",
    },
    {
        id: 5,
        name: "Sony 24-70mm f/2.8 GM II",
        brand: "Sony",
        cat: "Lensa",
        price: 150000,
        deposit: 450000,
        rating: 4.9,
        reviews: 28,
        hot: false,
        isNew: true,
        avail: true,
        icon: "🔭",
        desc: "Lensa zoom standard flagship Sony. Aperture f/2.8 konstan.",
    },
    {
        id: 6,
        name: "Softbox 60x60",
        brand: "Godox",
        cat: "Aksesoris",
        price: 50000,
        deposit: 100000,
        rating: 4.5,
        reviews: 10,
        hot: false,
        isNew: false,
        avail: true,
        icon: "🎒",
        desc: "Lighting softbox studio Godox untuk pencahayaan.",
    },
    {
        id: 7,
        name: "Tripod Aluminium",
        brand: "Vanguard",
        cat: "Aksesoris",
        price: 30000,
        deposit: 50000,
        rating: 4.6,
        reviews: 15,
        hot: false,
        isNew: false,
        avail: true,
        icon: "🎒",
        desc: "Tripod camera ringan dan kokoh untuk travel.",
    },
];
